Base const:
  G:  6.674e-11 # гравитационная постоянная
  stellar_constant:  1365 # звёздная постоянная [Вт/м]
  C:  4180 # удельная теплоёмкость воды
  R:  6371000
  alfa:  0.3977 #ось наклона земли
  Growth_constant: 1.5
  M: 5.9742e+24
  Md: 2.5e+13
Variable parameters:
  k:  (5.08 * 10**11)/(3.14 * R**2 * alfa)
  g:  (G*M)/(R**2)
  h:  Growth_constant/g
  #средняя температура планеты
  T:  k * stellar_constant
  #Энергия от солнечных панелей 
  E_silar_panel:  0.24 * stellar_constant
  #Энергия от ядерных реакторов
  E_nuclear_reactor:  (0.6 * 5555)/(C * 633)
Functions:
  food:
    arguments:
      - t
      - p
      - P
    formula: (30*(1+P/100)**(0.25*T * (h**2))- (P)) if (30*(1+P/100)**(0.25*T * (h**2))- (P)) > 0 else 0.00001
  energy:
    arguments:
      -p
      -P
      -energy
    formula:
      energy + (((0.00001*(E_silar_panel + E_nuclear_reactor) ) * (0.2*p)**1.2) - P) if energy + ((((E_silar_panel + E_nuclear_reactor) ) * p) - P) > 0 else 0.00001

  population:
    arguments:
      -t
      -food
      -energy
      -P
    formula:
      P + ((food * 0.00025 * energy)/5-P/5)
#      (energy*food)*P*(1 - P)
  resources:
    arguments:
      -res
      -p
      -E
    formula:
     res + (((p * E) - P)) if res + ((p + E) - P) > 0 else 0.00001
  Ax:
    arguments:
      -x
      -y
      -x0
      -y0


    formula: (G * Md * (x0 - x)) / (((x - x0)**2 + (y - y0)**2))**1.5

  Ay:
    arguments:
      -x
      -y
      -x0
      -y0


    formula: (G * Md * (y0 - y)) / (((x - x0)**2 + (y - y0)**2))**1.5





